CREATE DATABASE QUANLYNHATHUOC

GO
SET DATEFORMAT DMY

GO
USE QUANLYNHATHUOC

GO
CREATE TABLE THUOC
(
	MaThuoc VARCHAR(20) PRIMARY KEY,
	TenThuoc NVARCHAR(100) NOT NULL,
	HoatChat NVARCHAR(200) NOT NULL,
	GiaNhap INT NOT NULL,
	GiaSauThue INT NOT NULL,
	GiaBan INT NOT NULL,
	ThoiHanSuDung INT NOT NULL
)

GO
CREATE TABLE DUOCSY
(
	MaDuocSy VARCHAR(10) PRIMARY KEY,
	TenDuocSy VARCHAR(30) NOT NULL,
	BangCap VARCHAR(20) NOT NULL,
	NgayVaoLam DATE NOT NULL,
	Luong INT NOT NULL
)

GO
CREATE TABLE DONBAN
(
	MaDonThuoc VARCHAR(10) PRIMARY KEY,
	LoaiDon INT NOT NULL,
	NgayBan DATE NOT NULL,
	MaDuocSy VARCHAR(10) NOT NULL REFERENCES DUOCSY(MaDuocSy),
	TacDung NVARCHAR(200)
)

GO
CREATE TABLE CTDONTHUOC
(
	MaDonThuoc VARCHAR(10) NOT NULL REFERENCES DONBAN(MaDonThuoc),
	MaThuoc VARCHAR(20) NOT NULL REFERENCES THUOC(MaThuoc),
	SoLuong INT NOT NULL,
	NgayHetHan DATE NOT NULL,
	LoaiDonThuoc INT NOT NULL,
	CONSTRAINT PK_CTDONTHUOC PRIMARY KEY(MaDonThuoc, MaThuoc)
)

GO
CREATE TABLE CONGTY
(
	MaCongTy VARCHAR(20) PRIMARY KEY,
	TenCongTy NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE DONNHAP
(
	MaDonThuoc VARCHAR(10) PRIMARY KEY,
	NgayNhap DATE NOT NULL,
	MaCongTy VARCHAR(20) NOT NULL REFERENCES CONGTY(MaCongTy),
	MaDuocSy VARCHAR(10) NOT NULL REFERENCES DUOCSY(MaDuocSy) 
)

GO
CREATE TABLE KHO
(
	MaThuoc VARCHAR(20) NOT NULL REFERENCES THUOC(MaThuoc),
	MaDonThuoc VARCHAR(10) NOT NULL REFERENCES DONNHAP(MaDonThuoc),
	SoLuong INT NOT NULL,
	NgayHetHan DATE NOT NULL,
	CONSTRAINT PK_KHO PRIMARY KEY(MaThuoc, MaDonThuoc)
)

GO
CREATE TABLE TAIKHOAN
(
	TaiKhoan VARCHAR(30) PRIMARY KEY,
	MatKhau NVARCHAR(100) NOT NULL,
	MaDuocSy VARCHAR(10) NOT NULL REFERENCES DUOCSY(MaDuocSy)
)

GO
CREATE TABLE QUYEN
(
	TaiKhoan VARCHAR(30) NOT NULL REFERENCES TAIKHOAN(TaiKhoan),
	BanThuoc INT NOT NULL,
	NhapThuoc INT NOT NULL,
	ThongKe INT NOT NULL,
	CONSTRAINT PK_QUYEN PRIMARY KEY(TaiKhoan, BanThuoc)
)

INSERT INTO THUOC (MaThuoc, TenThuoc , HoatChat ,GiaNhap ,GiaSauThue ,GiaBan ,ThoiHanSuDung ) VALUES ('MT001', 'berberin','Chữa đau bụng',8000,9000,10000,3);

select MaThuoc 'Mã Thuốc', TenThuoc 'Tên Thuốc', HoatChat 'Hoạt Chất',GiaNhap 'Giá Nhập',GiaSauThue 'Giá Sau Thuế',GiaBan 'Giá Bán',ThoiHanSuDung 'Thời Hạn Sử Dụng'  from THUOC